language: node_js

branches:
  only:
  - master
  - stable

jobs:
  include:
    - stage: 'Deploy'
      name: 'Deploy test site'
      caches:
        - node
      script:
        .travis/deploy_site.sh
    - stage: 'Deploy'
      name: 'Deploy to npmjs'
      caches:
        - node
      script:
        .travis/deploy_lib.sh
