language: node_js

branches:
  except:
    - dependabot
    - dependabot/*
  only:
    - master
    - stable

jobs:
  include:
    - stage: 'Deploy'
      name: 'Deploy to npmjs'
      caches:
        - node
      script:
        .travis/deploy.sh
