language: node_js

branches:
  except:
    - dependabot
    - dependabot/*
  only:
    - master
    - stable

jobs:
  include:
    cache:
      - node_modules
    - script: .travis/deploy-ugla.sh
      name: Deploy Ugla
    - script: .travis/deploy-ugla-rules.sh
      name: Deploy Rules
