language: node_js

branches:
  except:
    - dependabot
    - dependabot/*
  only:
    - master
    - stable

jobs:
  include:
    - stage: 'Deploy Ugla'
      name: 'Deploy Ugla to npmjs'
      cache:
        - node_modules
      script: .travis/deploy-ugla.sh
      script: .travis/deploy-ugla-rules.sh
