name: Deploy Ugla Rules

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache node modules
      uses: actions/cache@v1
      env:
        cache-name: cache-node-modules
      with:
        path: |
          ~/.npm
          node_modules/
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-build-${{ env.cache-name }}-
          ${{ runner.os }}-build-
          ${{ runner.os }}-
    
    - uses: actions/setup-node@v1
      with:
        node-version: 14
        registry-url: https://registry.npmjs.org/

    - name: Install dependencies
      run: npm i
    
    - name: Generate file version
      run: node -e 'require("./version").changeConfig()';
      
    - name: Build library
      run: node_modules/.bin/ng build --project=ugla-rules
  
    - name: Move LICENSE
      run: cp -r LICENSE dist/ugla-rules
    
    - name: Deploy
      run: cd dist/ugla-rules/ && npm publish
      env:
        NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
    
    - name: Send message Telegram
      uses: appleboy/telegram-action@master
      with:
        to: ${{ secrets.TELEGRAM_TO }}
        token: ${{ secrets.TELEGRAM_TOKEN }}
        message: |
          New build by Ugla Rules
          The ${{ github.event_name }} event triggered final step.
