name: Deploy Ugla

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Config npm
      run: printf "//`node -p \"require('url').parse('https://registry.npmjs.org').host\"`/:_authToken=${NPM_TOKEN}\nregistry=${NPM_REGISTRY_URL:-https://registry.npmjs.org}\n" >> ~/.npmrc

    - name: Install dependencies
      run: npm i

    - name: Cache node_modules
      uses: actions/cache@v2
      with:
        path: |
          **/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    
    - name: Generate file version
      run: node -e 'require("./version").changeConfig()';
      
    - name: Build library
      run: npm run build --project=ugla
    
    - name: Move sass
      run: cp -r projects/ugla/src/sass $GITHUB_WORKSPACE/dist/ugla
  
    - name: Move LICENSE
      run: cp -r LICENSE $GITHUB_WORKSPACE/dist/ugla
    
    - name: Deploy
      run: cd $GITHUB_WORKSPACE/dist/ugla && npm publish
